<?php

use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Capsule\Manager as DB;

class DeleteFiltersWhereCampaignInList extends Migration {

  /**
   * Run the migrations.
   *
   * @return void
   */
  public function up()
  {
    DB::statement("  
      UPDATE tbl_filters set deleted = 1
      WHERE campaign_id IN (
        SELECT ca.id
        FROM
        tbl_campaigns ca
        INNER jOIN tbl_clients c ON ca.client_id=c.id
        WHERE c.name IN
        ('313Y',
        '375',
        '48 Fitzroy',
        'Agenda Design',
        'Alchemy V',
        'All Of Us',
        'Allen Design Group',
        'Amanda',
        'Amethist',
        'an.x',
        'AND Partners',
        'APR',
        'Arc Integrated Marketing',
        'ARM DIRECT Ltd',
        'AsOne',
        'Attik',
        'Barrett Howe',
        'BEcause',
        'Bell Integrated Communications Ltd',
        'Bestoutcome',
        'Blue Dog Design Ltd',
        'Bluesoup Communications',
        'Bounce Digital',
        'Brand Environment',
        'Brandpool',
        'Brocklebank Penn',
        'Bullet Marketing',
        'Busara',
        'Campaign Creative',
        'CDP',
        'Circus Street',
        'ClickTag',
        'CLIENT X',
        'Clinic',
        'Cloudspotting',
        'Codegent',
        'Coleman Moore',
        'Colourgraphic Arts',
        'Columns Design',
        'Communique PR',
        'Creative Lynx',
        'Cross-Tab',
        'Cunningham Design',
        'Curious',
        'Dawson Walker',
        'DDM',
        'Demographik Ltd',
        'Design Group',
        'Designers Anonymous',
        'Designlab',
        'Deviate',
        'Devilfish',
        'Direct Consult',
        'Drive Business',
        'Duke',
        'Duttons',
        'Earnest (London) Ltd',
        'Earth Branding',
        'Enlogic',
        'Entire',
        'Equi=Media',
        'Etre',
        'Factorydesign',
        'Fantastic Thinking',
        'FK3',
        'Flourish Creative Marketing',
        'Forepoint',
        'Found',
        'Fountain',
        'Fourtold',
        'Fraser Design Associates Limited',
        'fst',
        'Fusion Creative Marketing',
        'Gekko Partners',
        'Goosebumps Brand Consultancy',
        'Grappa/Hannover Consultancy',
        'Greenrow',
        'Haslimann Taylor',
        'Hawaii Design',
        'Hilite DMS',
        'Hit Search',
        'Howard Hunt Group',
        'HQ Graphics',
        'HSAG',
        'ICU',
        'Id*a',
        'Impact IM',
        'Incredibull Ideas',
        'Ink Creatiions',
        'Intelligent Positioning',
        'Jeffries Parsons Myers Harvey',
        'JohnstonWorks',
        'Kaboom Creative Ltd',
        'Kaizo PR',
        'Kaizo',
        'Kastner Partners',
        'Katana',
        'Klein and Sons',
        'Landau Reece',
        'Lean',
        'Madhouse Property',
        'Magnetic Advertising Company Ltd',
        'Mandate',
        'Mangostorm',
        'Marketing And Design Matters Ltd',
        'Marketing Means',
        'MCBX',
        'Media Circus Group',
        'Merchant Design',
        'MK Group',
        'Mousetrap',
        'Mtivity',
        'Mullis Morgan',
        'MultiAdaptor',
        'Mutual Ideas',
        'My Design Company',
        'N2O',
        'Northone Sport',
        'Ontrac',
        'Open Communications',
        'Orbital Response',
        'Origin Creative Design',
        'Page Nine',
        'Parker Williams',
        'Pemberton & Whitefoord',
        'PER Design',
        'PGK Advertising',
        'Picture',
        'Positive Digital',
        'Positive Group',
        'Pragma Consulting Ltd',
        'Prevision Limited',
        'Promodus',
        'Propeller Group',
        'PSH',
        'Punch Comms',
        'Purple Circle',
        'Purple Frog',
        'Quantum Analytics',
        'Radford Wallis',
        'Rapier - Project Mice',
        'Ratcliffe Fowler',
        'Rawls & Company',
        'Red Dog Communications',
        'RedMoran',
        'Redweb',
        'Reprise Media',
        'Republic PR',
        'Robson Dowry',
        'Sadek Wynberg Millward Brown',
        'Salix Consulting',
        'Schawk',
        'Semantic',
        'Shoal Creative',
        'Sightline',
        'Siren-PHD',
        'SmartFusion',
        'Soak Digital',
        'Soapbox Creative Marketing Ltd',
        'Social',
        'Spinach',
        'Sportiv8',
        'Spotlight',
        'Spread Design Ltd',
        'SSG Create',
        'Studio 2BR',
        'Suburb Design',
        'Swordfish 2007',
        'TC Communications',
        'Techworks Asia',
        'Templar Downie',
        'Teqtonic Ltd',
        'The Futures Company',
        'The Ransom Group',
        'The Real Adventure',
        'The Team',
        'The Think Tank',
        'Thirty3above',
        'Thorneycroft Bell',
        'Threesixty Communications',
        'Transmission Marketing',
        'Trumpet',
        'Tsuko',
        'Userview',
        'Velti',
        'Verve Marketing London',
        'Victoria',
        'Visuality',
        'Visuality_1',
        'Vivid Lime',
        'Walker Agency Ltd',
        'We Are Branding',
        'Web Liquid Ltd',
        'Wide Area Communications',
        'William Joseph',
        'WIN Plc',
        'Work Communications',
        'Yard Partners',
        'Yomego',
        'You Gov Consulting',
        'Zoocha')
        )
    ");
  }

  /**
   * Reverse the migrations.
   *
   * @return void
   */
  public function down()
  {
    DB::statement("  
      UPDATE tbl_filters set deleted = 0
      WHERE campaign_id IN (
        SELECT ca.id
        FROM
        tbl_campaigns ca
        INNER jOIN tbl_clients c ON ca.client_id=c.id
        WHERE c.name IN
        ('313Y',
        '375',
        '48 Fitzroy',
        'Agenda Design',
        'Alchemy V',
        'All Of Us',
        'Allen Design Group',
        'Amanda',
        'Amethist',
        'an.x',
        'AND Partners',
        'APR',
        'Arc Integrated Marketing',
        'ARM DIRECT Ltd',
        'AsOne',
        'Attik',
        'Barrett Howe',
        'BEcause',
        'Bell Integrated Communications Ltd',
        'Bestoutcome',
        'Blue Dog Design Ltd',
        'Bluesoup Communications',
        'Bounce Digital',
        'Brand Environment',
        'Brandpool',
        'Brocklebank Penn',
        'Bullet Marketing',
        'Busara',
        'Campaign Creative',
        'CDP',
        'Circus Street',
        'ClickTag',
        'CLIENT X',
        'Clinic',
        'Cloudspotting',
        'Codegent',
        'Coleman Moore',
        'Colourgraphic Arts',
        'Columns Design',
        'Communique PR',
        'Creative Lynx',
        'Cross-Tab',
        'Cunningham Design',
        'Curious',
        'Dawson Walker',
        'DDM',
        'Demographik Ltd',
        'Design Group',
        'Designers Anonymous',
        'Designlab',
        'Deviate',
        'Devilfish',
        'Direct Consult',
        'Drive Business',
        'Duke',
        'Duttons',
        'Earnest (London) Ltd',
        'Earth Branding',
        'Enlogic',
        'Entire',
        'Equi=Media',
        'Etre',
        'Factorydesign',
        'Fantastic Thinking',
        'FK3',
        'Flourish Creative Marketing',
        'Forepoint',
        'Found',
        'Fountain',
        'Fourtold',
        'Fraser Design Associates Limited',
        'fst',
        'Fusion Creative Marketing',
        'Gekko Partners',
        'Goosebumps Brand Consultancy',
        'Grappa/Hannover Consultancy',
        'Greenrow',
        'Haslimann Taylor',
        'Hawaii Design',
        'Hilite DMS',
        'Hit Search',
        'Howard Hunt Group',
        'HQ Graphics',
        'HSAG',
        'ICU',
        'Id*a',
        'Impact IM',
        'Incredibull Ideas',
        'Ink Creatiions',
        'Intelligent Positioning',
        'Jeffries Parsons Myers Harvey',
        'JohnstonWorks',
        'Kaboom Creative Ltd',
        'Kaizo PR',
        'Kaizo',
        'Kastner Partners',
        'Katana',
        'Klein and Sons',
        'Landau Reece',
        'Lean',
        'Madhouse Property',
        'Magnetic Advertising Company Ltd',
        'Mandate',
        'Mangostorm',
        'Marketing And Design Matters Ltd',
        'Marketing Means',
        'MCBX',
        'Media Circus Group',
        'Merchant Design',
        'MK Group',
        'Mousetrap',
        'Mtivity',
        'Mullis Morgan',
        'MultiAdaptor',
        'Mutual Ideas',
        'My Design Company',
        'N2O',
        'Northone Sport',
        'Ontrac',
        'Open Communications',
        'Orbital Response',
        'Origin Creative Design',
        'Page Nine',
        'Parker Williams',
        'Pemberton & Whitefoord',
        'PER Design',
        'PGK Advertising',
        'Picture',
        'Positive Digital',
        'Positive Group',
        'Pragma Consulting Ltd',
        'Prevision Limited',
        'Promodus',
        'Propeller Group',
        'PSH',
        'Punch Comms',
        'Purple Circle',
        'Purple Frog',
        'Quantum Analytics',
        'Radford Wallis',
        'Rapier - Project Mice',
        'Ratcliffe Fowler',
        'Rawls & Company',
        'Red Dog Communications',
        'RedMoran',
        'Redweb',
        'Reprise Media',
        'Republic PR',
        'Robson Dowry',
        'Sadek Wynberg Millward Brown',
        'Salix Consulting',
        'Schawk',
        'Semantic',
        'Shoal Creative',
        'Sightline',
        'Siren-PHD',
        'SmartFusion',
        'Soak Digital',
        'Soapbox Creative Marketing Ltd',
        'Social',
        'Spinach',
        'Sportiv8',
        'Spotlight',
        'Spread Design Ltd',
        'SSG Create',
        'Studio 2BR',
        'Suburb Design',
        'Swordfish 2007',
        'TC Communications',
        'Techworks Asia',
        'Templar Downie',
        'Teqtonic Ltd',
        'The Futures Company',
        'The Ransom Group',
        'The Real Adventure',
        'The Team',
        'The Think Tank',
        'Thirty3above',
        'Thorneycroft Bell',
        'Threesixty Communications',
        'Transmission Marketing',
        'Trumpet',
        'Tsuko',
        'Userview',
        'Velti',
        'Verve Marketing London',
        'Victoria',
        'Visuality',
        'Visuality_1',
        'Vivid Lime',
        'Walker Agency Ltd',
        'We Are Branding',
        'Web Liquid Ltd',
        'Wide Area Communications',
        'William Joseph',
        'WIN Plc',
        'Work Communications',
        'Yard Partners',
        'Yomego',
        'You Gov Consulting',
        'Zoocha')
        )
    ");
  }

}
