# global variables
pageTitle   = "Main Menu"
bodyBgColor = #000000
tableBgColor = #000000
rowBgColor  = #00ff00

# table/read-only row colours used by various templates
readColor1  = #f5f5f5
readColor2  = #e0e0e0


# Wednesday 3 January, 2007
format_date_long = "%A %e %B %Y"

# Wed 3 Jan 2007
format_date_short_with_day = "%a %e %b %y"

# 3 Jan 2007
format_date_short = "%e %b %y"

# Wednesday 3 January 2007 at 09:51:16
format_datetime_long = "%A %e %B %Y at %H:%M:%S"

# Wed 3 Jan 07 at 09:51
format_datetime_short = "%a %e %b %y at %H:%M"

# 09:51:16
format_time_long = "%H:%M:%S"

# 09:51
format_time_short = "%H:%M"




[Customer]
pageTitle = "Customer Info"

[Login]
pageTitle = "Login"
focus = "username"
Intro = """This is a value that spans more
           than one line. you must enclose
           it in triple quotes."""

# hidden section
[.Database]
host=my.example.com
db=ADDRESSBOOK
user=php-user
pass=foobar